### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by CepheiA2** [p4535992/foundryvtt-token-factions#21]
**Module Version:** v0.3.3

**Describe the bug**
With the latest update of "Token Faction" the borders are drawn below the tokens and they are visible only when you hover them with the mouse.

*Console Log*
Uncaught (in promise) Error: This is not a registered game setting
[Detected 2 packages: token-factions, lib-wrapper]
    at ClientSettings.get (foundry.js:2758:42)
    at debug (lib.js:14:23)
    at TokenFactions.drawBorderFaction (tokenFactions.js:552:13)
    at TokenFactions.updateTokenFaction (tokenFactions.js:84:27)
    at tokenFactions.js:45:27
    at Array.forEach (<anonymous>)
    at TokenFactions.updateTokenDataFaction (tokenFactions.js:44:16)
    at Token5e.TokenPrototypeRefreshHandler (module.js:139:19)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁Token.prototype.refresh#0 (libWrapper-wrapper.js:189:20)
    at Token5e.draw (foundry.js:25090:10)
    at async Promise.all (index 42)
    at async TokenLayer._draw (foundry.js:30691:5)
    at async TokenLayer._draw (foundry.js:36752:5)
    at async TokenLayer.draw (foundry.js:30210:5)
    at async InterfaceCanvasGroup.draw (foundry.js:26040:9)
    at async InterfaceCanvasGroup.draw (foundry.js:38933:5)
    at async Canvas.draw (foundry.js:23576:11)
    at async Scene.view (foundry.js:20815:7)

**To Reproduce**
Just use FoundryVTT Vanilla with the Token Faction Active

**Expected behavior**
in previous versions the border was drawn over the token, and always visible.

**Screenshots**
![image](https://user-images.githubusercontent.com/85868381/198907503-3ea1e10f-2604-46fe-9643-827de26e7760.png)

**Browser:**
Chrome

**Foundry Version:** 
v10 build 288

**Game System:** 
DnD 5e

**Additional context**
Active Modules: 
Token Faction
libwrapper

**Comment by p4535992** [comment]
I solved the bug on my side, but the border behaviour is lost with fvtt10 simply because the pixi frame is no more connected to the token but to the canvas himself.
You can override that by using the border control module and expand the border radius 1 or 2px or reduce the faction radius by1 or 20x.
